// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bazaDanych.Models;

#nullable disable

namespace bazaDanych.Migrations
{
    [DbContext(typeof(BazaDbContext))]
    partial class BazaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bazaDanych.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "[\"Action\",\"Fabular\"]",
                            Platform = "[\"Steam\",\"GOG\"]",
                            ReleaseDate = "19.05.2015",
                            Title = "Wiedźmin 3: Dziki Gon"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "[\"Action\",\"Fabular\"]",
                            Platform = "[\"Steam\",\"Rockstar Games Luncher\"]",
                            ReleaseDate = "26.10.2004",
                            Title = "Wielcy Złodzieje Aut: Święty Andrzej"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
